# Server config
server:
  port: ${PORT:8701}

logging:
  level:
    ROOT: INFO
    org.springframework.security: TRACE

info:
  component: Engine service

# Spring config
spring:
  mvc:
    log-request-details: true

  application:
    name: engine-service
  sleuth:
    enabled: true
  zipkin:
    enabled: true
    base-url: ${ZIPKIN_SERVER:http://localhost:9411/}

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driver-class-name: org.h2.Driver
    hikari:
      idle-timeout: 10000
    sql:
      init:
        data-locations*:
          - data.sql
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update

# Eureka config
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka
  instance:
    hostname: localhost


feign:
  compression:
    request:
      enabled: true
      mime-types:
        - text/xml,application/xml,application/json
  autoconfiguration:
    jackson:
      enabled: true


clients:
  fraud:
    url: ${FRAUD_URL:http://localhost:8700/}


# Ribbon config
ribbon:
  eureka:
    enabled: true

# endpoints:
#   routes:
#     sensitive: false
#   trace:
#     sensitive: false

# Health management
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always