# Server config
server:
  port: ${PORT:8761}

# Spring config
spring:
  application:
    name: spring-cloud-discovery-service
  sleuth:
    enabled: true
  zipkin:
    enabled: true
    base-url: http://localhost:9411/
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driver-class-name: org.h2.Driver
    hikari:
      idle-timeout: 10000
    #  sql:
    #    init:
    #      data-locations*:
    #        - data.sql
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    defer-datasource-initialization: true
    hibernate:
    ddl-auto: update

# Eureka config
eureka:
  server:
    enableSelfPreservation: false
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka

# Health management
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always