spring:
  application:
    name: eureka-discovery-server-service
  sleuth:
    enabled: true
  zipkin:
    enabled: true
    base-url: ${ZIPKIN_SERVER:http://localhost:9411/}
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driver-class-name: org.h2.Driver
    hikari:
      idle-timeout: 10000
    #  sql:
    #    init:
    #      data-locations*:
    #        - data.sql
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    defer-datasource-initialization: true
    hibernate:
    ddl-auto: update

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

server:
  port: ${port:8761}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always