# Server config
server:
  port: ${PORT:8700}

logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG

info:
  component: Fraud service

# Spring config
spring:
  application:
    name: fraud-service
  sleuth:
    enabled: true
  zipkin:
    enabled: true
    base-url: ${ZIPKIN_SERVER:http://localhost:9411/}

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driver-class-name: org.h2.Driver
    hikari:
      idle-timeout: 10000
    sql:
     init:
       data-locations*:
         - data.sql
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update



# Eureka config
eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka
    registerWithEureka: false
    fetchRegistry: false

# Ribbon config
ribbon:
  eureka:
    enabled: true

# endpoints:
#   routes:
#     sensitive: false
#   trace:
#     sensitive: false

# Health management
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always