spring:
  application:
    name: fraud-microservice
  sleuth:
    enabled: true
  zipkin:
    enabled: true
    base-url: ${ZIPKIN_SERVER:http://localhost:9411/}
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driver-class-name: org.h2.Driver
    hikari:
      idle-timeout: 10000
  #  sql:
  #    init:
  #      data-locations*:
  #        - data.sql
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update




server:
  port: ${port:8700}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always


#  spring.datasource.username=sa
#  spring.datasource.password=password
#  spring.datasource.driverClassName=org.h2.Driver
#  spring.jpa.database-platform=org.hibernate.dialect.H2Dialect



#techefx-product-stock-service:
#  ribbon:
#    listOfServers: http://localhost:8800, http://localhost:8801