# Server config
server:
  port: ${PORT:8900}

logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG

info:
  component: API Gateway

# Spring config
spring:
  application:
    name: spring-cloud-api-gateway-service
  zipkin:
    enabled: true
    base-url: http://localhost:9411/
  cloud:
    discovery:
      enabled: true
    gateway:
      routes:
        - id: engine-engine
          uri: lb://engine-service:8701/
          predicates:
            - Path=/**
        - id: fraud-service
          uri: lb://fraud-service:8702/
          predicates:
            - Path=/**


# Eureka config
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka
  instance:
    preferIpAddress: true

# Ribbon config
ribbon:
  eureka:
    enabled: true

endpoints:
  routes:
    sensitive: false
  trace:
    sensitive: false

# Health management
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always