# Server config
server:
  port: ${PORT:8900}

logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG

info:
  component: API Gateway

# Spring config
spring:
  application:
    name: spring-cloud-api-gateway-service
  zipkin:
    enabled: true
    base-url: http://localhost:9411/
  cloud:
    gateway:
      routes:
        - id: engine-service
          uri: http://localhost:8800/
          predicates:
            - Path=/engine/**
        - id: fraud-service
          uri: http://localhost:8700/
          predicates:
            - Path=/fraud/**

# Eureka config
eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka
    registerWithEureka: false
    fetchRegistry: false

# Ribbon config
ribbon:
  eureka:
    enabled: true

# Zuul config
# zuul:
#   prefix: /api
#   routes:
#     engine:
#       path: /engine/**
#       serviceId: engine-service
#     fraud:
#       path: /fraud/**
#       serviceId: fraud-service

endpoints:
  routes:
    sensitive: false
  trace:
    sensitive: false

# Health management
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always