spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          skip-ssl-validation: true
          uri: https://github.com/lisci/microservice-architecture.git
          search-paths:
            - feature_spring_cloud_config_properties

server:
  port: ${port:8888}

