spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          skip-ssl-validation: true
          uri: https://github.com/lisci/spring-cloud-config-properties.git
          # search-paths:
          #   - feature_spring_cloud_config_properties

server:
  port: ${port:8888}

